# Generated by Django 4.1.5 on 2023-01-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('modalidade', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
